[package]
name = "memory"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#slint = {version = "0.2", features = ["std", "backend-gl-wayland", "compat-0-2-0"]}
slint = "0.2.1"
rand = "0.8"
